/****** Object:  Database [bread]    Script Date: 02/08/2020 19:36:12 ******/
CREATE DATABASE [bread]  (EDITION = 'GeneralPurpose', SERVICE_OBJECTIVE = 'GP_Gen5_2', MAXSIZE = 32 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO
ALTER DATABASE [bread] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [bread] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [bread] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [bread] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [bread] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [bread] SET ARITHABORT OFF 
GO
ALTER DATABASE [bread] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [bread] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [bread] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [bread] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [bread] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [bread] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [bread] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [bread] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [bread] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [bread] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [bread] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [bread] SET  MULTI_USER 
GO
ALTER DATABASE [bread] SET ENCRYPTION ON
GO
ALTER DATABASE [bread] SET QUERY_STORE = ON
GO
ALTER DATABASE [bread] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
/****** Object:  Table [dbo].[Matcon]    Script Date: 02/08/2020 19:36:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Matcon](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[Name] [nvarchar](200) NOT NULL,
	[Data] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Matcon] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MatconRating]    Script Date: 02/08/2020 19:36:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MatconRating](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MatconId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
	[Timestamp] [datetime] NOT NULL,
	[Rating] [int] NOT NULL,
	[Data] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_MatconRating] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MatconTag]    Script Date: 02/08/2020 19:36:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MatconTag](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MatconId] [int] NOT NULL,
	[Tag] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_MatconTag] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PreRegister]    Script Date: 02/08/2020 19:36:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PreRegister](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](320) NOT NULL,
	[Token] [char](100) NOT NULL,
	[Timestamp] [datetime] NOT NULL,
	[EmailValidated] [bit] NOT NULL,
 CONSTRAINT [PK_PreRegister] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 02/08/2020 19:36:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](320) NOT NULL,
	[Data] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserAuth]    Script Date: 02/08/2020 19:36:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserAuth](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[Data] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_UserAuth] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Matcon]    Script Date: 02/08/2020 19:36:13 ******/
CREATE NONCLUSTERED INDEX [IX_Matcon] ON [dbo].[Matcon]
(
	[Name] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_User_Email]    Script Date: 02/08/2020 19:36:13 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_User_Email] ON [dbo].[User]
(
	[Email] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PreRegister] ADD  CONSTRAINT [DF_PreRegister_EmailValidated]  DEFAULT ((0)) FOR [EmailValidated]
GO
ALTER TABLE [dbo].[Matcon]  WITH CHECK ADD  CONSTRAINT [FK_Matcon_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Matcon] CHECK CONSTRAINT [FK_Matcon_User]
GO
ALTER TABLE [dbo].[MatconRating]  WITH CHECK ADD  CONSTRAINT [FK_MatconRating_Matcon] FOREIGN KEY([MatconId])
REFERENCES [dbo].[Matcon] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[MatconRating] CHECK CONSTRAINT [FK_MatconRating_Matcon]
GO
ALTER TABLE [dbo].[MatconRating]  WITH CHECK ADD  CONSTRAINT [FK_MatconRating_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[MatconRating] CHECK CONSTRAINT [FK_MatconRating_User]
GO
ALTER TABLE [dbo].[MatconTag]  WITH CHECK ADD  CONSTRAINT [FK_MatconTag_Matcon] FOREIGN KEY([MatconId])
REFERENCES [dbo].[Matcon] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[MatconTag] CHECK CONSTRAINT [FK_MatconTag_Matcon]
GO
ALTER TABLE [dbo].[UserAuth]  WITH CHECK ADD  CONSTRAINT [FK_UserAuth_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserAuth] CHECK CONSTRAINT [FK_UserAuth_User]
GO
ALTER DATABASE [bread] SET  READ_WRITE 
GO
